fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_profile_edit:
    resource: "@UserBundle/Resources/config/profile.xml"
user:
    resource: "@UserBundle/Controller/"
    type: annotation